[Feature] 기프티콘 추가 API
Team-BuddyCon/BACKEND_V2 pull request #20
Opened 2023-10-06 13:59 UTC by shinyubin989

### 변경사항
- aws s3 dependency 추가
- gifticon내에 barcode 필드 제거, userId 필드추가
- ApiResponse의 success메소드 분리 (body의 유무)
- s3에 Image 업로드 담당 컴포넌트 추가
- GifticonStore, GifticonStoreCategory의 패키지 변경 (adapter -> domain) 
- AuthUser가 필요한 통합테스트에서 사용할 Mock ArgumentResolver 추가
- 기프티콘 추가 도메인 로직 및 테스트 로직 추가

2023-10-08 10:14 UTC, Huey-J requested changes
수고하셨습니다! 👍👍👍 

코멘트 확인해 주시고, Conflict 해결 부탁드려요~~

2023-10-08 10:14 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/adapter/infra/entity/GifticonEntity.java
>    @Column(name = "image_url", nullable = false)
https://github.com/Team-BuddyCon/BACKEND_V2/pull/14 에서 작업한 내용과는 다르게 작업하셨군요.

저도 이 부분은 계속 고민이 됩니다. 도메인 별로 비즈니스 로직을 전부 나누었으니 DB도 연관관계를 맺지 않고 나누는게 좋지 않을까?라는 생각도 들고, 저희는 서버와 DB를 나누진 않을테니 RDBMS의 기능을 활용할 수 있도록 나누지 않는게 맞나? 생각도 듭니다. 🫠

2023-10-08 10:14 UTC, Huey-J commented on src/test/java/yapp/buddycon/app/gifticon/CreateGifticonControllerTest.java
> +
이 부분은 뭔가 많이 고생하셨을 것 같군요 ㅠㅠ 수고하셨습니다!

이미지 파일이 아닌 경우 처럼 파일 관련해서 오류가 있을 경우도 테스트 코드로 추가해 주면 좋을 것 같습니다. 이 부분은 따로 이슈 생성하셔서 작업해 주셔도 좋을 것 같아요~

2023-10-10 07:17 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/adapter/client/CreateGifticonController.java
> +    }
[만들면서 배우는 클린 아키텍처](https://product.kyobobook.co.kr/detail/S000001766486) 5장을 참고했습니다!
책에서는 컨트롤러를 세분화하지 않고 하나의 컨트롤러에서 요청을 처리하게되면 1)클래스에 코드의 양이 많아지고 기존코드에서 추가된 코드에 대한 내용을 파악하기 어려워짐 2)코드가 길어지면 테스트코드를 찾는데 어려움이 있음 < 과같은 문제가 발생할 수 있다고 설명해주었는데요,
제 경우에도 하나의 컨트롤러에서 동작을 처리하다보니 컨트롤러의 테스트코드가 길어지게 되었고 원하는 테스트코드를 찾기 힘들어져서 컨트롤러를 기능에따라 분리해야할 필요성이 있다고 느끼게되었어요

Command, Query로 나누지 않은 이유는 Command에 INSERT, UPDATE, DELETE 세가지 목적이 모두 포함되기때문에 위와같은 단점을 해결할 수 없다고 생각했고, 
또 저희가 Command와 Query로 분리한 이유는 db locking, 레플리케이션 등 DB동작 시에 차이가 있어 책임에 따라 분리한 목적이 있는데, Controller가 DB동작에따라 분리될 이유가 없다고 판단했습니다!

2023-10-10 07:28 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/common/validation/ValidatedEnum.java
> +}
400번대 에러를 exceptionhandler에서 핸들링할 수 있나요?!

2023-10-10 07:33 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/adapter/infra/entity/GifticonEntity.java
>    @Column(name = "image_url", nullable = false)
아 이 부분 작업하다보니, JPA의 연관관계 매핑을 사용하면 특정 도메인에서 타 도메인에 의존하게되고 (GifticonEntity가 UserEntity를 의존) 이에따라 도메인들이 분리되지않아 DDD에 위반된다고 생각해서 Long타입으로 정의해두었습니다! 
이 방식도 말씀해주신 RDBMS의 기능을 이용할 수 있을거같아용

2023-10-11 00:29 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/common/validation/ValidatedEnum.java
> +}
넵. IllegalArgumentException, BindException, MethodArgumentNotValidException 등으로 핸들링 할 수 있었던 것 같습니다!
이 부분도 개선의 영역이니 따로 이슈로 등록해서 추후 진행해도 좋을 것 같네용

2023-10-17 15:33 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
@Huey-J Builder와 create메서드는 어떤 구분을 두고 사용하는게 좋을까요??🧐

2023-10-18 04:12 UTC, fin2b-hhjang commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
create 메소드가 항상 create 메소드로만 생성 가능하도록 제한하는게 좋을 것 같습니다.
builder를 아예 제거하거나 `@Builder(access = AccessLevel.PRIVATE)` 처럼 access 제한을 하는건 어떠신가요?

2023-10-18 04:12 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
create 메소드가 항상 create 메소드로만 생성 가능하도록 제한하는게 좋을 것 같습니다.
builder를 아예 제거하거나 @Builder(access = AccessLevel.PRIVATE) 처럼 access 제한을 하는건 어떠신가요?

2023-10-18 04:18 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
혹시 빌더대신 메서드를 사용하시려는 이유가 있으실까요!

2023-10-18 04:23 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
저는 주로 메소드를 사용해서 그런데, 빌더를 사용했을 때 필수값이 잘 들어갔는지 알 수 있는 방법이 있나요? 저는 이 부분 때문에 create 메소드를 사용하고자 했습니다.

2023-10-18 04:27 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
혹시 그러면 생성자대신 create메서드가 가진 이점이 있을까요?

2023-10-18 05:14 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
흠 명시적인 이유 말고는 생각나는게 없군요. 오버로딩 측면에서도 같으니까요. 🤔

2023-10-18 05:16 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
생성자가 아닌 create 메소드라면 안에 비즈니스 로직이 들어갈 것 같아요. 그리고 테스트 코드도 작성해야 할 것 같구요.

2023-10-18 05:24 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
[이펙티브자바 2장 - 생성자에 매개변수가 많다면 빌더를 고려하라](https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-2.-%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EA%B0%80-%EB%A7%8E%EB%8B%A4%EB%A9%B4-%EB%B9%8C%EB%8D%94%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC) 
롬복에서 제공해주는 빌더말고 커스텀 빌더 이너클래스를 만들면 좋을거같은데 어떠실까요~~
필수필드와 선택필드를 구분할 수 있고, 우려하신 필수값이 잘 들어갔는지도 보장해주네요! 메서드체이닝으로 가독성도 좋을거같구요

2023-10-18 05:34 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
오 좋습니다! ㅎㅎ 이걸로 가시죠~!!  😄 👍

2023-10-19 06:20 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/gifticon/application/service/CreateGifticonService.java
> +        Gifticon gifticon = new Gifticon(null, userId, imageUrl, dto.name(), dto.memo(), dto.expireDate(), false, dto.store(), dto.store().getCategory());
현희님 이부분 생각해봤는데, 생성자랑 차이가 없네요.. ㅜㅜ
필수필드는 기존방식대로 생성자로 생성해야하는데, 메모 필드 빼고는 다 필수필드라 생성자 방식과 다를게 없는것같아요

일단 그냥 생성자로 갈까요? ㅎ....

2023-10-20 08:15 UTC, merged