[Feature] auth 로직
Team-BuddyCon/BACKEND_V2 pull request #7
Opened 2023-08-07 08:48 UTC by shinyubin989

## 구현사항 👀
- 카카오 oauth를 이용하여 자체 서비스 로그인 로직을 구현하였습니다.
  - 카카오 oauth의 경우, webclient(webflux dependency)를 사용하여 api를 호출하였습니다.
    - 이 과정에서 올바르지않은 액세스토큰이거나, 카카오서버에 문제가 있을경우 OAuthRequestException이 발생합니다.
  - 카카오 oauth로부터 clientId를 받아옵니다.
    - 서비스 디비에 해당 clientId가 없을 경우 디비에 save합니다.
    - clientid가 있는경우 save하지않고 그대로 가져옵니다.
  - db로부터 가져온 사용자의 id를 이용해 jwt 토큰을 발급합니다.
<br>

## 논의가 필요한사항 🙋🏻‍♀️ 
1. 어플리케이션의 도메인들을 총괄하는 패키지 명을 'web'에서 -> 'app(application)' 혹은 'domains' 등으로 변경하는건 어떨까요? web이라는 패키지명이 해당 패키지의 역할을 제대로 설명하지 않는것 같다고 생각해요!
2. domain패키지내에 @Entity클래스를 둬서 해당 패키지내에 스프링의존성을 갖는것보다, adapter영역에서 이를 pojo<->entity로 매핑해주는 건 어떨까요? 
    ```java
    @RequiredArgsConstructor
    @Component
    public class JpaUserCommandPort implements UserCommandPort {
    
        private final JpaUserRepository jpaUserRepository;
        private final UserMapper mapper;
    
        @Override
        public User save(User user) {
            return mapper.toUser(jpaUserRepository.save(mapper.toEntity(user)));
        }
    }
    ```
    - 위는 코드의 예시인데요, 매핑 클래스(UserMapper)를 만들어놓은 후 port들에서 query,command를 할때 매핑해주는 식으로 구현했습니다.
    - 위 방법의 장점 : domain, application 패키지 내에는 스프링 부트 의존성을 대부분 없앱니다 (스프링 빈 등록 어노테이션 제외)
3. infra패키지의 레벨을 adapter의 하위에 두는게 어떨까요? 기존에 adapter.out에서 jpa 영속성을 담당했듯이, 외부 기술에 의존하는 것들은 adapter의 하위에 위치하는게 맞는거같다고 생각됩니다.

2023-08-07 10:55 UTC, ritty27 reviewed
배고파서 밑에는 남겨놨어요.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/application/port/out/TokenCreator.java
> +public interface TokenCreator {
TokenCreator interface가 필요한 이유는 무엇인가요?
application 영역 내에서 TokenCreator는 쓰이지 않고 있고, TokenProvider에 구현체에서만 TokenCreator의 구현체를 사용하고 있어요. TokenCreator를 추상화해서 얻는 이점이 어떤 것이 있죠?

아래의 내용을 고민해보세요.
- TokenCreator를 적용하지 않았을 때 의존성 방향에 문제가 생기는가?
- TokenCreator interface의 불별식이 따로 존재하는가?
- JwtTokenCreator 말고 TokenCreator의 테스트가 존재하는가?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/application/service/RealTime.java
> +import java.util.Date;
Java에 Date는 Deprecated 되었어요.
이유를 알고 계시나요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/common/config/RedisConfig.java
> +class RedisConfig {
TokenCreator와 비슷한 맥락인데요.
CahcePort의 존재 해야할까요? 현재 RedisTokenPort가 어디에서 사용되고 있는지 살펴보세요.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/application/port/out/CachePort.java
> +public interface CachePort {
Object보단 Generic을 사용해 보는건 어떨까요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/common/response/ApplicationException.java
> +public class ApplicationException extends RuntimeException{
ApplicationException 말고 buddyconException은 어떨까요?
Application 패키지 내부에서만 사용하고 있는 상황도 아니고 buddycon 시스템 전반에 사용되는 예외로 보여요.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/common/response/ApiResponse.java
> +    public static ResponseEntity<?> success(String message, Object body) {
ApiResponse가 StatusCode가 200, 404, 500 외에는 사용하기 어려운 구조인것 같은데요.
현재는 새로운 StatusCode를 내려주려면 method를 추가해야 할 것 같아요.

다른 방법은 없을까요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +        Token token = login.login(request.accessToken());
`Login::login` 뭔가 이상하게 느껴지시지 않나요?
객체 (class) / method 의 존재 이유/목표를 고민해보세요.

login은 동작 아닐까요?~

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +        Token token = login.login(request.accessToken());
`request.accessToken()` 을 현재 사용할 수 있는 이유는 login method에 parameter를 하나만 넘겨줘도 되기 때문인데요.
추후에 login method에 parameter 가 추가된다면 똑같이 request.param2() 같이 풀어서 login에 넘겨주실 건가요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/OAuthRequestException.java
> +    public OAuthRequestException(String message) {
OAuthRequestException이 발생할 때마다 message를 외부에서 받는 이유는 무엇일까요?
해당 예외의 책임은 정확히 무엇인가요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +@RequestMapping("/api/v1/auth")
postFix로 `/` 를 명시 해주는게 좋아보여요. 
login 요청에도 따로 prefix가 존재하지 않습니다.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/JwtTokenProvider.java
> +    Date accessTokenExpiresIn = new Date(now.getTime()+ACCESS_TOKEN_EXPIRE_TIME);
Auto formatting을 사용합시다.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/auth/adapter/JwtTokenProvider.java
> +    cachePort.saveWithExpiration(user.id().toString(), token.refreshToken(), REFRESH_TOKEN_EXPIRE_TIME);
cachePort 라는 이름을 보고 어떤 일을 하는 클래스인지 예상 하기 조금 어려워요.

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/user/adapter/infra/JpaUserCommandPort.java
> +public class JpaUserCommandPort implements UserCommandPort {
Port의 기준이 뭔가요?
Jpa는 구현 클래스인데 Port라는 이름이 맞는걸까요?

2023-08-07 10:55 UTC, ritty27 commented on src/main/java/yapp/buddycon/app/user/application/port/out/UserCommandPort.java
> +public interface UserCommandPort {
Command, Query의 네이밍은 기술 동작 방식을 기준으로 분리한 것으로 보입니다. (CQRS를 노리는건가요?)

application 패키지 내부의 클래스는 기술 동작 보단 도메인 로직을 표현해야 할 것 같아요.
-> CQRS는 우리의 기술적 도메인 로직이라고 생각하고 적용하신거면 현재 상태도 좋아 보입니다.

2023-08-07 10:55 UTC, ritty27 commented on src/test/java/yapp/buddycon/app/auth/JwtTokenCreatorTest.java
> +    Token token = jwtTokenCreator.createToken(user, testDate, testDate, testDate);
해당 테스트는 jwt 라이브러리를 테스트 하는 것처럼 보입니다.

createToken의 결과는 String 값입니다. -> 해당 String 값만으로는 테스트 불가능한 상황이기 때문에 복호화 코드를 만드신 것 같아요.
해당 테스트는 `accessToken을 만들 때 payload에 id를 넣었는데 이거 잘못 동작할 수 있는거 아냐?`로 보이고 결국 jwt를 테스트 하는 것 같아요.

2023-08-07 10:55 UTC, ritty27 commented on src/test/java/yapp/buddycon/app/auth/JwtTokenCreatorTest.java
> +    Token token = jwtTokenCreator.createToken(user, testDate, testDate, testDate);
해당 테스는 jwt 라이브러리를 테스트 하는 것처럼 보입니다.

2023-08-08 14:57 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/RealTime.java
> +import java.util.Date;
[commit 링크](https://github.com/Team-BuddyCon/BACKEND_V2/pull/7/commits/e814ed9fbba1ead8a6c3699ce4eb51bf81179a8d) 
말씀해주신 대로, deprecated된 Date에서 **Instant** 클래스로 변경하였습니다.

-> 처음에는 RealTime(현재는 LocalTime)클래스의 메소드가 **LocalDateTime**을 반환하도록 하게 했는데, RealTime클래스에 의존하는 JwtTokenCreator에서 토큰을 만들때 **ZoneId에 대한 의존성**을 가질 수 밖에 없게되었습니다. (LocalDateTime -> Date 변환과정에서)
이는 JwtTokenCreator의 관심사가 아니라고 판단하였고, LocalDateTime이 아닌 Instant를 매개변수로 받도록 변경하고, 후에 여러 도메인로직에서 현재 서버 시간대가 필요한 경우 UTC기준 Instant가 아닌, **현재 서버기준 시간**을 내려주는 책임이 있는 RealTime 클래스의 이름을 LocalTime로 변경하였습니다.

<br> 

**LocalDateTime 사용시**

```java
public class JwtTokenCreator implements TokenCreator {

  ...
  public Token createToken(User user, LocalDateTime accessTokenExpiresIn, LocalDateTime refreshTokenExpiresIn, LocalDateTime now) {

    var accessToken = Jwts.builder()
      .setIssuedAt(Date.from(now.atZone(ZoneId.systemDefault()).toInstant()))
      .setExpiration(Date.from(accessTokenExpiresIn.atZone(ZoneId.systemDefault()).toInstant()))

    // LocalDateTime을 사용시 JwtTokenCreator의 'Jwt 토큰을 생성한다'라는 책임과 맞지않는 의존성인 ZoneId가 필요하게됨.
  ...
  }
}

```


**Instant 사용시**
```java
public class JwtTokenCreator {
  public Token createToken(User user, Instant accessTokenExpiresIn, Instant refreshTokenExpiresIn, Instant now) {

    var accessToken = Jwts.builder()
      .claim("id", user.id())
      .setIssuedAt(Date.from(now))
      .setExpiration(Date.from(accessTokenExpiresIn))
    
    // Date.from()메소드에 Instant를 인자로 넘겨줄 수 있으므로 Zone에 대한 의존성이 불필요
    ...
  }
}
```

2023-08-08 14:59 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/port/out/TokenCreator.java
> +public interface TokenCreator {
[commit 링크](https://github.com/Team-BuddyCon/BACKEND_V2/pull/7/commits/7e8cf4530815b55129531f8d39b0fcca3e87bc19)

생각해보니 TokenCreator는 JwtTokenProvider(adapter영역)에서만 사용할 뿐, application영역에서 이를 직접적으로 사용하는 클래스가 없고 따라서 port.out에 있어야할 이유가 없다고 판단되어 제거하였습니다 !

2023-08-08 15:04 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +@RequestMapping("/api/v1/auth")
[commit 링크](https://github.com/Team-BuddyCon/BACKEND_V2/pull/7/commits/0c46d80b7b81582da3413294b0eab36864903f22)

수정했습니다 👍🏼

2023-08-08 15:07 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/user/application/port/out/UserCommandPort.java
> +public interface UserCommandPort {
말씀해주신 것처럼, 내부적으로 CQRS를 기술적 도메인 로직이라고 판단하고 클래스를 분리하였습니다!

2023-08-08 15:11 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/adapter/OAuthRequestException.java
> +    public OAuthRequestException(String message) {
```java
// kakao oauth 유저 정보 api 호출 로직 중 일부

return webClient.get()
            .headers(header -> {
              header.setBearerAuth(accessToken);
            })
            .retrieve()
            .bodyToMono(Kakao.class)
            .onErrorMap((error) -> new OAuthRequestException(error.getMessage()))
            .map(Kakao::toOAuthMember)
            .block();
```

OAuthRequestException의 경우 Kakao측에서 보내주는 에러 메시지가 경우에 따라 다르기때문에(401, 카카오 서버문제 등) OAuthRequestException내부에서 message를 명시하지 않았습니다. OAuthRequestException의 message는 webclient수행중 에러메시지를 받아오도록 구현하였습니다.

추후에 추가될 애플리케이션 내의 예외들에는 가능한 경우 Exception내부에서 자체적으로 message를 갖도록 구현할 예정입니다!

2023-08-08 15:14 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +        Token token = login.login(request.accessToken());
adapter영역의 dto라는 의존성을 application영역까지 끌고오고싶지 않아 controller에서 값을 꺼내 login에 인자로 전달하는 방식으로 구현하였는데,
이 부분은 추후에 application에도 dto를 둬서 adapter의 dto와 매핑해주는 방식 등 여러 방식을 고안해 본 후 수정해보도록 하겠습니다. 👍🏼

2023-08-08 15:20 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/common/config/RedisConfig.java
> +class RedisConfig {
기본적으로 여러 구현체들에게서 공통점을 관찰한 후 그것을 인터페이스로 뽑아내야하겠지만, 
이번 경우에는 추후에 '어떤 어떤 CachePort의 구현체를 만들어야겠다'라는 생각이 있었고 그 인터페이스를 미리 만들어놓으면 편하겠다-라는 생각으로 먼저 만들어놓았던것같습니다!

2023-08-08 15:22 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/common/response/ApplicationException.java
> +public class ApplicationException extends RuntimeException{
의도했던 것은 application계층의 Application이 아닌, 전체 서비스를 의미하는 Application이었지만 오해의 여지가 있다는 것에 동의합니다! 추후에 BuddyconException, CustomException 등등 적합한 이름을 고민해본 후 수정하도록 하겠습니다.

2023-08-08 15:29 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/adapter/LoginController.java
> +        Token token = login.login(request.accessToken());
[commit 링크](https://github.com/Team-BuddyCon/BACKEND_V2/pull/7/commits/a160f451b2290dd118c1727cab663296fbcf0e51)

login() -> execute()로 메서드명을 수정하였습니다. 100%마음에 드는 메서드명은 아니라서, 추후에 더 적합한 이름이 떠오르면 수정해보도록하겠습니다.

2023-08-15 04:46 UTC, Huey-J requested changes
안녕하세요 유빈님~ 제가 리뷰가 많이 늦었네요 죄송합니다ㅠㅠ

@ritty27 님 배고프신대도 너무 좋은 퀄리티의 PR리뷰 감사합니다ㅎㅎ 저도 많이 배울 수 있었네요~!


## 논의

1, 2, 3에 대한 내용은 다른 PR과 중복되는 내용이네요! https://github.com/Team-BuddyCon/BACKEND_V2/pull/6#issuecomment-1677689549 댓글에 의견 드렸습니다~

4번 예외처리는 두 번째 방법이 좋을 것 같습니다. 도메인 별로 exception을 정의하고 처리하는게 헥사고날에 어울릴 것 같아요.

추가로 제가 고민되는 내용은 패키지 구조입니다.
현재 구조가 같은 레벨의 클래스들끼리 잘 정리되어 있어서 헥사고날 기준으로 좋은 구조인 듯 합니다. 하지만, 개발자 입장에서는 좀 불편하지 않나 싶습니다. adapter가 너무 비대해져서 원하는 클래스를 찾기 어려워진 것 같아요. 앱이 고도화 되면 훨씬 더 복잡해질 것 같습니다.
adapter 패키지를 그 안에서 기능 별로 나누면 어떨까요? JWT 관련 패키지, 외부 API 호출 패키지, DB Connection 패키지 등으로 나누는거죠. 의견 부탁드립니다~

2023-08-15 04:46 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
SignUpDecider가 꼭 필요한 이유가 있을까요? Login에서 다 처리하는건 어떨까요?

2023-08-15 04:46 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/user/adapter/infra/JpaUserQueryStorage.java
> +
음 이 부분은 저도 고민되는데 port 를 suffix로 하는게 어떨까요? 헥사고날에서 port가 가지는 의미가 있으니까요?

2023-08-15 07:45 UTC, shinyubin989 commented
> 추가로 제가 고민되는 내용은 패키지 구조입니다. 현재 구조가 같은 레벨의 클래스들끼리 잘 정리되어 있어서 헥사고날 기준으로 좋은 구조인 듯 합니다. 하지만, 개발자 입장에서는 좀 불편하지 않나 싶습니다. adapter가 너무 비대해져서 원하는 클래스를 찾기 어려워진 것 같아요. 앱이 고도화 되면 훨씬 더 복잡해질 것 같습니다. adapter 패키지를 그 안에서 기능 별로 나누면 어떨까요? JWT 관련 패키지, 외부 API 호출 패키지, DB Connection 패키지 등으로 나누는거죠. 의견 부탁드립니다~

-> 동의합니다! 이부분도 따로 adapter영역에서 패키지 분리해서 커밋하도록 하겠습니다~~

2023-08-18 13:03 UTC, merged

2023-08-18 16:13 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
알겠습니다. 역할을 나누는 점에서 좋은 구조인 것 같네요 :)

아래는 다른 내용입니다!

1. LoginService.execute()의 메소드 명은 추후 로그아웃, 회원탈퇴 등의 API가 추가될 경우를 대비해서 변경하는게 어떨까요?
2. oauth로 받은 accessToken과 저희가 발급한 accessToken의 변수명이 같아서 헷갈릴 여지가 있는듯 합니다.
3. Token 클래스가 고민이 많이 되는데요, 웹 요청에 대한 응답 DTO이면서 하고 계층간 VO 역할도 수행하고 있습니다. 제 아이디어는 해당 클래스를 TokenResponseDTO으로 변경하여 응답값의 역할만 수행하도록 하고, TokenProvider와 TokenCreator를 합친 후 createAccessToken(), createRefreshToken()로 메소드를 나누어 호출하는건 어떨까 싶은데 유빈님 생각은 어떠신가요?

2023-08-19 07:43 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
1. 넵!좋습니다 그러면 LoginService->AuthService로 클래스명을 변경하고 execute()->login()으로 메서드명 변경하도록 하겠습니다.
2. oauth로 받은 accessToken을 oauthAccessToken으로 지정할까 합니다!
3. TokenCreator에서 createAccessToken(), createRefreshToken()메소드를 가지게 하고, LoginService에서 두 메소드를 호출해서 TokenResponseDto로 넘겨주는 형태라면 application에서 adapter의 DTO에 의존하게되지는 않을까요??

2023-08-19 10:06 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
3. 저는 그 정도의 의존은 어쩔 수 없다고 생각합니다ㅠㅠ 혹시 유빈님은 다른 아이디어가 있으신가요?

2023-08-19 10:55 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
음음 혹시 Token이 웹 요청에 대한 응답 DTO이면서 계층간 VO 역할도 수행할때 생길 문제점은 뭐가있을까요??

2023-08-19 11:31 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/Login.java
> +}
흠 생각해보니 JPA에서도 DTO로 직접 반환하여 Service로 넘겨주는 것과 같은 맥락으로 볼 수 있겠군요.
클래스명에 Suffix만 붙혀주시면 될 것 같습니다!