[Fix] auth 로직
Team-BuddyCon/BACKEND_V2 pull request #9
Opened 2023-08-23 13:40 UTC by shinyubin989

## 변경사항
1. UserEntity에 닉네임, 이메일, 성별, 연령대 필드 추가
2. Token -> TokenDto 네이밍 변경
3. Controller테스트를 MockMvc에서 RestAssured로 변경
   1. BDD스타일의 메소드 체이닝 기법으로 작성이 가능해, 가독성을 향상시킬 수 있었습니다.
   2. MockMvc의 content메소드는 byte[], String만을 매개변수로 받기때문에, request body를 넘겨줄때 String으로 넘겨줘야하는 문제가 있었습니다.    String으로 넘겨주는 경우 만약 비즈니스 로직 상 request 형식이 바뀌면 test의 request string도 바꿔줘야 했습니다. RestAssured을 사용하면서 json data를 객체로서 쉽게 다룰 수 있었습니다.
   3. MockMvc로 request body를 작성할 때 body에 담기는 내용이 많으면 test given절에서 body에 담을 string절을 만드는 데에 많은 줄이 소요되었습니다.   
      ```java
      final var body = """
                    {
                        "oauthAccessToken":"%s",
                        "nickname":"nickname",
                        "email":"email",
                        "gender":"FEMALE",
                        "age":"10-20"
                    }
                """.formatted(invalidAccessToken);
      ```
      예를들어 위와같이 request에 필드가 많으면 given절이 테스트 내에서 차지하는 비중이 커졌습니다.
   4. 입력을 Dto 객체로 만들고, gson의 `ObjectMapper.writeValueAsString(dto)`를 사용하면 객체를 스트링으로 변환해주기 때문에 입력을 String으로 관리하지않아도 됐지만, 각 메소드마다 테스트의 목적과 상관없는 메소드를 중복적으로 사용하는 것을 피하고자 하였습니다.

2023-08-24 19:01 UTC, Huey-J requested changes
고민되는 부분과 궁금한 내용 코멘트 남겼습니다. 😀
Controller 테스트 역시 저희는 공부가 목적이니 지금처럼 둘 다 사용해 보면서 익혀보는게 좋을 것 같습니다.

코멘트 외에 또 고민되는 내용이 있는데요. 또또또 패키지..! 또키지 구조 관련 내용입니다.ㅎㅎ
아래 내용이 큰 작업이면 PR을 따로 가져가는게 좋을 것 같습니다.

### 1. auth 패키지와 user 패키지 의존성

저희가 app 패키지 내부는 도메인 기준으로 나누고자 했습니다. 하지만 auth와 user는 높은 결합도를 가지고 있는데요. 이는 AuthService에서 User의 도메인 객체를 사용하는 걸 보면 알 수 있습니다.

제가 생각하는 방법은 총 2가지인데요. 우선 첫 번째는 비교적 간단한 방법인데 두 패키지를 합치는 방식입니다. 추후 Controller가 두 개인 형태로 발전할 수도 있을 것 같아요.

두 번째 방법은 스프링 이벤트를 사용하는 방법입니다. 도메인 기준으로 패키지를 나눌 때 많이 사용하는 방식이라고 알고 있어서 정석일 수 있지만, 현재 저희 단계에서는 잘못하면 오버 엔지니어링이 될 수도 있습니다.

### 2. common 패키지 위치

위에서 말씀드린 것 처럼 app 패키지 내부는 도메인 기준으로 나눕니다. 하지만 common 패키지는 특정 도메인에 속하지 않고, 도메인이라고 보기도 어려우니 app 패키지의 바깥으로 빼면 어떨까요?

2023-08-29 15:29 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/user/adapter/jpa/UserMapper.java
>      }
자문자답 입니다만, 찾아보니 아래와 같이 정리할 수 있겠네요. 🫠

1. Domain 계층의 Pojo와 영속성 계층의 엔티티를 나눠야 하는 이유 

데이터베이스는 단순히 지속성 구현의 세부 사항에 불과하다. 따라서 핵심 도메인은 Pojo로써 개발하고 DB에 저장될 객체와 나누자. 정리하자면 애플리케이션을 데이터베이스를 위해 만드는 것이 아니라 도메인을 위해 만드는 것이 중요하다.
https://blog.sapiensworks.com/post/2012/04/07/Just-Stop-It!-The-Domain-Model-Is-Not-The-Persistence-Model.aspx

2. Mapper의 필요성

계층간 결합도를 낮추기 위함이다. 도메인 객체는 어떤 계층에도 의존하지 않도록 하여 역할&책임에 집중하도록 하자.

2023-08-30 03:14 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/LoginRequest.java
> +) {
1. 넵~~!
2. 
<img width="856" alt="image" src="https://github.com/Team-BuddyCon/BACKEND_V2/assets/69676101/601abd44-d9fb-40f3-97b7-0a717b85f6fb">
카카오에서 다음과같이 String형식으로 넘겨줍니다.   

3. 다시 adapter로 변경하겠습니다! 특별한 이유는 없었고 application이 adapter를 의존하지않도록 임시적으로 옮겼었는데, 좋은 방법은 아닌거같네요 ㅜ

2023-08-30 03:28 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
음 저는 caller입장에서 db에 새로운 유저가 저장되는지 예상할 수 없는게 장점이라고 생각했습니다! 사실 장점이라기보다는 예상하지 않아도 된다고 생각했고, SignUp을 Decider측에서 캡슐화시키기 위해서 userQueryStorage.findByClientId()가 Optional 반환값을 가지고 Optional인지 아닌지에따라 Decider가 저장만 시키면 된다는 책임을 가지고있다고 생각했습니다.

메서드를 분리시킨다면 어떤식으로 분리하면 좋을까요??

2023-08-31 03:46 UTC, shinyubin989 commented
> 1. auth 패키지와 user 패키지

음음 저는 2번 아니면 현재의 방식으로 가는게 어떨까 싶은데요, 관점에 따라 다르겠지만 저의 경우 auth가 user 도메인 객체를 사용하고 있지만 auth의 역할과 user의 역할은 분리되어있다고 생각하기 때문입니다. 
auth의 경우 jwt토큰 암호화/복호화, argument resolver 등으로 Authorization, kakao oauth client 등 인증과 관련된 책임이 있고, 이는 user의 영역이 아니라고 생각했습니다.

2번으로 하게된다면 이벤트라는 새로운 개념을 학습할 수 있고 도메인간에 격리시킬 수 있다는 장점이 있을 것 같아요. 
현재의 방식으로 한다면 auth에서 user를 사용하게되는 점은 있지만, auth에서 user를 직접적으로 건드린다기보다는 user에서 정의된 바를 auth에서 따르는 형식이고, 주로 user의 port interface를 사용하기 때문에 
auth내에서는 주로 메서드나 반환타입으로서의 User 도메인 객체를 사용하므로 이 나름대로도 괜찮을 것 같다는 생각도있습니다.

> 2. common 패키지 위치

넵넵 좋습니다 이부분은 머지된 후에 진행하도록 해요!

2023-09-01 00:20 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
DB 조회나 생성 쿼리가 발생하는 등의 동작은 캡슐화의 장점보다는 예상치 못한 사이드 이펙트의 리스크가 더 크다고 생각했습니다.
그래서 메소드 명에 이를 표시해주어 caller 입장에서 내부의 동작을 알고 사용하도록 하면 어떨까 싶었습니다.

메소드 분리를 위해 로그인에 대한 비즈니스 로직을 간단하게 정리해 봤습니다.

1. 요청받은 oAuth 토큰으로 API 호출을 통해 userId를 가져온다.
2. 받아온 userId로 DB에 저장된 유저가 있는지 확인하고, 없다면 생성하여 가져온다.
3. 유저 정보를 통해 JWT 토큰을 반환한다.

현재의 SignUpDecider의 역할도 Service가 하는건 어떨까요? AuthService가 Api 호출, DB 조회, JWT 반환을 각각 책임이 있는 클래스의 메소드에게 전달하는 방식입니다. 이렇게 되면 Service 코드만 봐도 비즈니스 로직에 대한 이해가 갈 수 있어서 명세의 장점도 있다고 생각합니다.

+ 헥사고날 아키텍처에서 맞는 사고 방식인지는 저도 의문이 드네요. 🫠

2023-09-01 00:31 UTC, Huey-J commented
> 1. auth 패키지와 user 패키지

흐음 어렵군요. 제가 이해하기엔 A 도메인의 application 계층이 B 도메인의 도메인 계층에 접근하려면 다시 port, adapter를 타고 나갔다가 B 도메인의 application으로 들어와서 처리되어야 한다고 생각했습니다. 각각 다른 헥사고날 원을 가지고 있는거죠.
따라서 역할이 분리되어 있어서 도메인을 나누었다면 헥사고날 측면에서 확실한 분리가 필요하지 않을까 싶습니다.

그런 의미에서 저는 유빈님 말씀대로 2번 방식도 좋은 것 같습니다!

2023-09-01 00:41 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
그렇게 되면 AuthService 입장에서 아래 정도만 표시될 것 같아요.

1. 제공자는 모르지만 oAuth 토큰으로 userId를 가져오고,
2. 어딘지는 모르지만 영속성 계층에서 user 도메인을 가져오고, 없으면 저장하여 가져오고,
3. 해당 user 도메인으로 JWT토큰을 발행하여 반환한다.

2023-09-01 05:45 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
현희님이 생각하시는 예상치못한 사이드 이펙트의 리스크는 예를들어 어떤경우가 있을까요??

2023-09-03 07:13 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
> 예상치못한 사이드 이펙트의 리스크는 어떤 경우가 있을까요?

맨 처음에 말씀 드린 내용과 같습니다. caller 입장에서 decide 메소드 호출 만으로 DB에 새로운 유저가 추가되는 걸 예상하기 어렵고, DB 추가에 대한 작업을 숨기기엔 너무 중요한 로직이라고 생각해요.
SignUpDecider.decide() 는 회원가입을 해야 할지 말아야 할지에 대한 boolean 값을 반환하는 메소드로 이해하기 쉽다고 생각합니다.
메소드 명만 바꾼다면 decideWithApiAndRepository() 같은 메소드명은 어떤가요? 🤔

> AuthService가 여러가지 책임을 가져가게 되고

Service에서 여러 책임을 가져가는것 처럼 보이지만 하나의 큰 요구사항(API 호출)을 작은 단위로 쪼개고 각 클래스 메소드를 호출함으로써 책임을 위임한다는 책임을 가진다고 생각하는건 어떨까요?

2023-09-03 09:07 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
login이라는 책임에서 봤을때, db에 새로운유저가 추가되는지를 알아야하는 이유가있을까요?? 그저 login은 db로부터 유저id를 가져와서 그에맞는 토큰을 반환한다는 것만 알면 되지않을까요?
db에 새로운유저를 추가했는지 알아야할 필요가 있을지, 알지못한다면 어떤 위험이 발생할지 궁금합니다!

2023-09-03 14:59 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
아하 이제 유빈님 의도가 좀 이해가 가는군요.

로그인과 관련된 책임을 SignUpDecider에게, 토큰과 관련된 책임을 TokenProvider에게 각각 할당하였고, DB작업을 포함한 로그인 관련 로직은 Service가 알 필요가 없으니 의존성을 줄이고자 Service에서는 분리하신 거군요.

제가 우려했던 점(위험)은 코드 가독성 측면에서 말씀드린 거였습니다. 여러 번 말씀드린 것 처럼 개발자 입장에서, 그리고 caller 입장에서 클래스명과 메소드명 만으로 어떤 동작을 하는지 바로 이해하기는 힘들 것 같다고 생각했어요. 읽기 쉬운 코드를 위해 약간의 의존성을 희생하고 Service를 비즈니스 로직의 명세 역할을 할 수 있도록 트레이드 오프 하는게 어떨까 싶었습니다.

정리해보면 캡슐화 측면에서는 좋지만 가독성 측면에서 아쉬움이 있다고 생각합니다!

2023-09-06 08:19 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
코멘트가 조금 늦었네요 😅
음 제가 Service 클래스에서 모든 역할을 수행하도록 하는것을 피하고 싶은 이유는 
첫번째로 추후에 AuthService클래스에 메소드가 많아지고, 해당 서비스클래스에서 모든 도메인 요구사항을 다룬다면 그 자체로 fat service class가 될 위험성이 있기때문입니다. 
또한, 서비스클래스에서 작업을 총괄하게된다면 그 자체로 해당 서비스는 변경의 이유가 많아지고, 단일책임을 벗어납니다. 사실 저는 서비스라는 네이밍도 그리 좋은 네이밍은 아니라고 생각이 되는데, 책임을 규명짓기 어렵고 또한 책임의 영역이 뚜렷해지지 못하기 때문입니다. '서비스'라는 이름하에 다양한 책임을 지니게 되고, 말씀하신것처럼 하나의 로직이 어떤어떤 의존성을 불러와 요구사항을 해결하는지는 한눈에 볼수있고 가독성이 올라가지만 제 생각에 이는 역으로 말하면 클래스 하나에 책임이 너무 많은 것이라고 볼 수도 있을거같아요.
둘째로, 서비스에서 모든 의존성들을 불러와 한곳에서 해결한다면 해당 서비스클래스는 많은 의존성클래스들에 엮이게되고, 이에따라 테스트를 할때에도 하나의 기능을 테스트하는데 테스트의 목적과 맞지않는 다수의 모킹을 해야하므로 테스트의 목적이 떨어지고 가독성 또한 떨어집니다. 

클래스와 메소드의 네이밍의 불분명함은 저도 현희님이 말씀해주시고 제3자의 입장에서 코드를 읽는다고 생각해보니 
SignupDecider 등의 네이밍이 로그인이라는 메소드에 등장할 네이밍이 아니라서 읽는데 물음표가 떠오를 수 있겠다 싶은데요, 말씀해주신 문제는 위와같은 생각을 기반으로 클래스명/메소드명을 수정해서 해결해보고싶은데 어떻게 생각하실까요 ??

2023-09-07 08:29 UTC, Huey-J commented on src/main/java/yapp/buddycon/app/auth/application/service/SignUpDecider.java
>    }
저는 유빈님이 말씀해주신 장단점을 정 반대로 생각했습니다. 가독성을 위해 다른 것들을 감수하는게 낫지 않을까 싶었어요.
가독성을 포기하면서 까지 단일책임 원칙을 지켜야 하는지 고민이 되었고, 테스트도 각자의 하위 클래스에 대해 단위테스트를 진행하면 큰 무리가 없을 것 같다고 생각했습니다. 개인적으로 가독성을 더 중시하는 편이라서요 ㅎㅎ

결과적으로 저는 두 방법 모두 장단점이 있다고 생각해서 말씀대로 클래스명/메소드명 수정하는 방식으로 진행해주시면 될 것 같습니다. 별도의 PR로 진행해도 좋을 것 같아요~

2023-09-07 10:07 UTC, Huey-J approved these changes

2023-09-08 05:59 UTC, closed without merging